This is makeindex, version 2.15 [TeX Live 2013] (kpathsea + Thai support).
Scanning style file ./thesis.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file thesis.acn....done (21 entries accepted, 0 rejected).
Sorting entries....done (132 comparisons).
Generating output file thesis.acr....done (36 lines written, 0 warnings).
Output written in thesis.acr.
Transcript written in thesis.alg.
